repos:
  - repo: local
    hooks:
      - id: black
        name: black via poetry
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]

      - id: isort
        name: isort via poetry
        entry: poetry run isort
        language: system
        types: [python]
        stages: [commit]

      - id: pytest
        name: pytest via poetry
        entry: poetry run pytest
        language: system
        pass_filenames: false
        stages: [commit]
