yfinance:
  IndBovespa: "^BVSP"
  IndNasdaq: "^IXIC"
  IndSp500: "^GSPC"
  IndDji : "^DJI"
  BtcUsd: "BTC-USD"
  EurUsd: "EURUSD=X"
  FutOuro: "GC=F"
  FutPrata: "SI=F"
  futCobre: "HG=F"
  FutPetroleo: "CL=F"
  FutOleo: "HO=F"
  FutGasNatural: "NG=F"
  FutGasolina: "RB=F"
  FutAcucar: "SB=F"
  FutMilho: "ZC=F"
  FutArroz: "ZR=F"
  FutSoja: "ZS=F"
  FutCafe: "KC=F"
  FutGado: "LE=F"
  FutPorco: "HE=F"
  FutAlgodao: "CT=F"
  JurosFuturo: "ZB=F"

bcb:
  SELIC: 11
  CDI: 12
  SELIC_Anual: 1178
  SELIC_Meta_Anual: 432
  IPCA_Mensal: 433
  IGP_M_Mensal: 189
  INCC_Mensal: 192
  Indice_Condicoes_Econ_BR: 27574
  Indice_Condicoes_Econ_BR_USD: 29042
  Salario_Minimo: 1619
  IBC_BR: 24363
  Populacao_BR: 21774
  PIB_Trimestral_Real: 4380
  PIB_Anual_Corrente: 7326
  Deflator_Implicito_PIB: 1211

DataReader:
  DEXBZUS: BRL_USD
  CPIAUCSL: CPI_USA